// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
//import "@hotwired/turbo-rails"
import "controllers"
import "controllers/disable-right-click"
import "controllers/hambmenu"
import "controllers/faq"
import "controllers/shop"
import "controllers/deleteaccount"
import "controllers/portfolio"
import "controllers/datepicker"
import "controllers/alert"